package filtrarimagen;

import java.net.MalformedURLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Jorge Santana
 */
public class FrameForm extends javax.swing.JFrame {
    
    /**
     * Creates new form FrameForm
     */
    public FrameForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        allCheck = new javax.swing.JCheckBox();
        blueCheck = new javax.swing.JCheckBox();
        redCheck = new javax.swing.JCheckBox();
        greenCheck = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        supIzqRadio = new javax.swing.JRadioButton();
        supDchaRadio = new javax.swing.JRadioButton();
        infIzqRadio = new javax.swing.JRadioButton();
        infDchaRadio = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        try {
            lienzo = new filtrarimagen.Lienzo();
        } catch (java.net.MalformedURLException e1) {
            e1.printStackTrace();
        }
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)), "Configuración", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10))); // NOI18N

        allCheck.setSelected(true);
        allCheck.setText("Todos");
        allCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allCheckActionPerformed(evt);
            }
        });

        blueCheck.setSelected(true);
        blueCheck.setText("Azul");
        blueCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blueCheckActionPerformed(evt);
            }
        });

        redCheck.setSelected(true);
        redCheck.setText("Rojo");
        redCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redCheckActionPerformed(evt);
            }
        });

        greenCheck.setSelected(true);
        greenCheck.setText("Verde");
        greenCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                greenCheckActionPerformed(evt);
            }
        });

        jLabel1.setText("Canales de color:");

        buttonGroup.add(supIzqRadio);
        supIzqRadio.setText("Superior izquierda");
        supIzqRadio.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                supIzqRadioItemStateChanged(evt);
            }
        });

        buttonGroup.add(supDchaRadio);
        supDchaRadio.setSelected(true);
        supDchaRadio.setText("Superior derecha");
        supDchaRadio.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                supDchaRadioItemStateChanged(evt);
            }
        });

        buttonGroup.add(infIzqRadio);
        infIzqRadio.setText("Inferior izquierda");
        infIzqRadio.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                infIzqRadioItemStateChanged(evt);
            }
        });

        buttonGroup.add(infDchaRadio);
        infDchaRadio.setText("Inferior derecha");
        infDchaRadio.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                infDchaRadioItemStateChanged(evt);
            }
        });

        jLabel2.setText("Posición del logo (Esquina):");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(supIzqRadio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(supDchaRadio))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(infIzqRadio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(infDchaRadio))
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(blueCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(greenCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(allCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(redCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(81, 81, 81)))
                .addGap(31, 31, 31))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(allCheck)
                    .addComponent(redCheck)
                    .addComponent(supIzqRadio)
                    .addComponent(supDchaRadio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(blueCheck)
                    .addComponent(greenCheck)
                    .addComponent(infIzqRadio)
                    .addComponent(infDchaRadio))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1200, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addComponent(lienzo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 652, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addComponent(lienzo, javax.swing.GroupLayout.PREFERRED_SIZE, 652, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jLabel3.setText("Jorge Santana Lorenzo");

        jLabel4.setText("Francisco Javier Sánchez González");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void allCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allCheckActionPerformed
        if(allCheck.isSelected()) {
            redCheck.setSelected(true);
            greenCheck.setSelected(true);
            blueCheck.setSelected(true);
            lienzo.changeColorFilter(true, true, true);
        }
        allCheck.setSelected(true);
    }//GEN-LAST:event_allCheckActionPerformed

    private void blueCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blueCheckActionPerformed
        if(!blueCheck.isSelected()) {
            if(redCheck.isSelected() || greenCheck.isSelected()) {
                blueCheck.setSelected(false);
                allCheck.setSelected(false);
                lienzo.changeColorFilter(redCheck.isSelected(), greenCheck.isSelected(), false);
            } else {
                blueCheck.setSelected(true);
                JOptionPane.showMessageDialog(null, "Debes marcar al menos uno");
            }
        } else {
            blueCheck.setSelected(true);
            if(redCheck.isSelected() && greenCheck.isSelected()) {
                allCheck.setSelected(true);
            }
            lienzo.changeColorFilter(redCheck.isSelected(), greenCheck.isSelected(), true);
        }
    }//GEN-LAST:event_blueCheckActionPerformed

    private void redCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redCheckActionPerformed
        if(!redCheck.isSelected()) {
            if(greenCheck.isSelected() || blueCheck.isSelected()) {
                redCheck.setSelected(false);
                allCheck.setSelected(false);
                lienzo.changeColorFilter(false, greenCheck.isSelected(), blueCheck.isSelected());
            } else {
                redCheck.setSelected(true);
                JOptionPane.showMessageDialog(null, "Debes marcar al menos uno");
            }
        } else {
            redCheck.setSelected(true);
            if(greenCheck.isSelected() && blueCheck.isSelected()) {
                allCheck.setSelected(true);
            }
            lienzo.changeColorFilter(true, greenCheck.isSelected(), blueCheck.isSelected());
        }
    }//GEN-LAST:event_redCheckActionPerformed

    private void greenCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_greenCheckActionPerformed
        if(!greenCheck.isSelected()) {
            if(redCheck.isSelected() || blueCheck.isSelected()) {
                greenCheck.setSelected(false);
                allCheck.setSelected(false);
                lienzo.changeColorFilter(redCheck.isSelected(), false, blueCheck.isSelected());
            } else {
                greenCheck.setSelected(true);
                JOptionPane.showMessageDialog(null, "Debes marcar al menos uno");
            }
        } else {
            greenCheck.setSelected(true);
            if(redCheck.isSelected() && blueCheck.isSelected()) {
                allCheck.setSelected(true);
            }
            lienzo.changeColorFilter(redCheck.isSelected(), true, blueCheck.isSelected());
        }
    }//GEN-LAST:event_greenCheckActionPerformed

    private void infDchaRadioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_infDchaRadioItemStateChanged
        int estado = evt.getStateChange();
        if(estado == 1) {
            lienzo.changeLogoPos(4);
        }
    }//GEN-LAST:event_infDchaRadioItemStateChanged

    private void supDchaRadioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_supDchaRadioItemStateChanged
        int estado = evt.getStateChange();
        if(estado == 1) {
            lienzo.changeLogoPos(2);
        }
    }//GEN-LAST:event_supDchaRadioItemStateChanged

    private void supIzqRadioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_supIzqRadioItemStateChanged
        int estado = evt.getStateChange();
        if(estado == 1) {
            lienzo.changeLogoPos(1);
        }
    }//GEN-LAST:event_supIzqRadioItemStateChanged

    private void infIzqRadioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_infIzqRadioItemStateChanged
        int estado = evt.getStateChange();
        if(estado == 1) {
            lienzo.changeLogoPos(3);
        }
    }//GEN-LAST:event_infIzqRadioItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox allCheck;
    private javax.swing.JCheckBox blueCheck;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JCheckBox greenCheck;
    private javax.swing.JRadioButton infDchaRadio;
    private javax.swing.JRadioButton infIzqRadio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private filtrarimagen.Lienzo lienzo;
    private javax.swing.JCheckBox redCheck;
    private javax.swing.JRadioButton supDchaRadio;
    private javax.swing.JRadioButton supIzqRadio;
    // End of variables declaration//GEN-END:variables
}
